import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';

import Layout from '@/components/layout/Layout';
import Hero from '@/components/hero';
import Services from '@/components/services';
import Products from '@/components/Products';
import BannerFirst from '@/components/banner/banner-first';
import Statistic from '@/components/statistic';
import Testimonial from '@/components/testimonial';
import BannerSecond from '@/components/banner/banner-second';

const HomePage: NextPage = () => {
	return (
		<Layout>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Hero />
			<Services />
			<Products />
			<BannerFirst />
			<Statistic />
			<Testimonial />
			<BannerSecond />
		</Layout>
	);
};

export default HomePage;
