import type { NextPage } from 'next';
import Head from 'next/head';

import Layout from '@/components/Layout/Layout';
import Hero from '@/components/Hero/Hero';
import Services from '@/components/Services/Services';
import Products from '@/components/Products/Products';
import BannerFirst from '@/components/Banner/banner-first/BannerFirst';
import Statistic from '@/components/Statistic/Statistic';
import Testimonial from '@/components/Testimonial/Testimonial';
import BannerSecond from '@/components/Banner/banner-second/BannerSecond';

const HomePage: NextPage = () => {
	return (
		<Layout>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Hero />
			<Services />
			<Products />
			<BannerFirst />
			<Statistic />
			<Testimonial />
			<BannerSecond />
		</Layout>
	);
};

export default HomePage;
