import type { NextPage } from 'next';
import Head from 'next/head';

import Layout from '@/components/layout/Layout';
import Hero from '@/components/hero/Hero';
import Services from '@/components/services/Services';
import Products from '@/components/products/Products';
import BannerFirst from '@/components/banner/banner-first/BannerFirst';
import Statistic from '@/components/statistic/Statistic';
import Testimonial from '@/components/testimonial/Testimonial';
import BannerSecond from '@/components/banner/banner-second/BannerSecond';

const HomePage: NextPage = () => {
	return (
		<Layout>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Hero />
			<Services />
			<Products />
			<BannerFirst />
			<Statistic />
			<Testimonial />
			<BannerSecond />
		</Layout>
	);
};

export default HomePage;
